name: flutter_multi_display
description: "A Flutter plugin for seamless multi-display Android apps with shared state across multiple Flutter engines."
version: 0.0.3
repository: https://github.com/WaqasShafi001/flutter_multi_display
homepage: https://github.com/WaqasShafi001/flutter_multi_display
issue_tracker: https://github.com/WaqasShafi001/flutter_multi_display/issues
documentation: https://pub.dev/documentation/flutter_multi_display/latest/

topics:
  - flutter
  - multi-display
  - multi-screen
  - shared-state
  - kiosk

keywords:
  - flutter
  - multiple-screens
  - secondary-display
  - shared-state
  - kiosk
  - presentation
  - pos
  - dual-screen
  - android-display

environment:
  sdk: ^3.9.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.github.waqasshafi001.flutter_multi_display
        pluginClass: FlutterMultiDisplayPlugin
